/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/3dassets/machine_guns.glb 
Author: Kingy (https://sketchfab.com/kingy)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/m60-machine-gun-vietnam-war-2f21855be3f545749239feaa5f1c8ff1
Title: M60 Machine Gun - Vietnam War
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function MachineGuns (props) {
  const { nodes, materials } = useGLTF('/3dassets/machine_guns.glb')
  return (
    <group {...props} dispose={null} scale={0.2}>
      <group position={[0, -13.196, -21.981]} rotation={[1.547, 0, 0.7]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.polySurface156_bits_m_0.geometry} material={materials.bits_m} rotation={[Math.PI / 2, 0, 0]} />
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.polySurface261_bulletsandcasings_0.geometry} material={materials.bulletsandcasings} />
            <mesh geometry={nodes.polySurface261_links_0.geometry} material={materials.links} />
            <mesh geometry={nodes.polySurface261_bits_m_0.geometry} material={materials.bits_m} />
            <mesh geometry={nodes.polySurface261_lambert1_0.geometry} material={materials.lambert1} />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.polySurface285_bits_m_0.geometry} material={materials.bits_m} />
            <mesh geometry={nodes.polySurface285_body_m_0.geometry} material={materials.body_m} />
          </group>
          <group position={[0, -17.601, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.polySurface315_bits_m_0.geometry} material={materials.bits_m} position={[0, 0, 5.421]} />
            <mesh geometry={nodes.polySurface319_bits_m_0.geometry} material={materials.bits_m} position={[0, 0, 5.421]} />
            <mesh geometry={nodes.polySurface321_bits_m_0.geometry} material={materials.bits_m} position={[0, 0, 5.421]} />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.polySurface320_bits_m_0.geometry} material={materials.bits_m} />
            <mesh geometry={nodes.polySurface320_body_m_0.geometry} material={materials.body_m} />
          </group>
          <group position={[5.322, -41.469, -5.541]} rotation={[-Math.PI / 2, -0.957, -Math.PI]}>
            <mesh geometry={nodes.polySurface346_lambert1_0.geometry} material={materials.lambert1} />
            <mesh geometry={nodes.polySurface346_bulletsandcasings_0.geometry} material={materials.bulletsandcasings} />
            <mesh geometry={nodes.polySurface346_links_0.geometry} material={materials.links} />
          </group>
          <mesh geometry={nodes.polySurface239_body_m_0.geometry} material={materials.body_m} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.polySurface245_body_m_0.geometry} material={materials.body_m} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.polySurface284_bits_m_0.geometry} material={materials.bits_m} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.polySurface248_bits_m_0.geometry} material={materials.bits_m} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.polySurface237_body_m_0.geometry} material={materials.body_m} rotation={[Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3dassets/machine_guns.glb')
