/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/3dassets/test_tubes/scene.gltf 
Author: Alex Krush (https://sketchfab.com/Alex_Krush)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chemical-test-tubes-ce3fdd3279584c2eaf416894dd36a81e
Title: Chemical Test Tubes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function TestTubeSet (props) {
  const { nodes, materials } = useGLTF('/3dassets/test_tubes/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.11} position={[-0.6,-1,0]}>
        <group position={[12.019, 1.672, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.tube_5_Polystyrene002_0.geometry} material={materials['Polystyrene.002']} />
          <mesh geometry={nodes.tube_5_Glass_0.geometry} material={materials.Glass} />
        </group>
        <mesh geometry={nodes.tube_8_Glass_0.geometry} material={materials.Glass} position={[50.856, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.tube_3_Glass_0.geometry} material={materials.Glass} position={[-9.249, 1.175, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.tube_4_Glass_0.geometry} material={materials.Glass} position={[-0.002, 1.175, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.tube_2_Glass_0.geometry} material={materials.Glass} position={[-23.12, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.tube_7_Glass_0.geometry} material={materials.Glass} position={[36.986, -0.464, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.tube_1_Glass_0.geometry} material={materials.Glass} position={[-38.839, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.tube_6_Glass_0.geometry} material={materials.Glass} position={[23.115, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/3dassets/test_tubes/scene.gltf')
