/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/atom.glb 
Author: rosaliarenda (https://sketchfab.com/rosaliarenda)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/atom-82993cead2024da28265a6a1580325a5
Title: atom
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Atom (props) {
  const { nodes, materials } = useGLTF('/3dassets/atom.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Sphere_0.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.BezierCircle001_0.geometry} material={materials['Material.002']} rotation={[0, -Math.PI / 3, 0]} scale={3.627} />
        <mesh geometry={nodes.BezierCircle002_0.geometry} material={materials['Material.002']} rotation={[Math.PI, -Math.PI / 3, Math.PI]} scale={3.8} />
        <mesh geometry={nodes.BezierCircle003_0.geometry} material={materials['Material.002']} scale={3.978} />
        <mesh geometry={nodes.Sphere002_0.geometry} material={materials['Material.003']} position={[3.9, 0, 0]} scale={0.3} />
        <mesh geometry={nodes.Sphere003_0.geometry} material={materials['Material.003']} position={[-1.9, 0, 3.29]} scale={0.3} />
        <mesh geometry={nodes.Sphere004_0.geometry} material={materials['Material.003']} position={[-1.81, 0, -3.14]} scale={0.3} />
      </group>
    </group>
  )
}

useGLTF.preload('/3dassets/atom.glb')
