/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/plant_cell.glb 
Author: Vida Systems (https://sketchfab.com/objects1)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/plant-cell-cell-structure-1c5ce80d03d149208d30cc5aeb6e42fb
Title: Plant Cell - Cell Structure
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function PlantCell (props) {
  const { nodes, materials } = useGLTF('/3dassets/plant_cell.glb')
  return (
    <group {...props} dispose={null} scale={[0.035,0.035,0.035]} position={[0,0,0]} rotation={[-1.5,0,3.15]}>
      <mesh geometry={nodes.cytoplasm_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[0, -18.039, 8.297]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.chloroplastin_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[8.496, 32.576, -26.908]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.chloroplastout_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[3.755, 28.838, -27.544]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.nucleus_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[-24.123, -0.873, -23.891]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.ribosomes_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[9.757, -9.492, 39.45]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.roughER_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[-20.645, -23.387, 9.16]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.golgiappratus_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[0.978, 0.049, -1.954]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.lysosome_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[0.978, 0.049, 0.059]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.peroxisome_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[0.978, 0.049, 0.059]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.vacuole_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[0.978, 0.049, 0.059]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.plasmodesma_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[0.978, 0.049, 0.059]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.cell_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[0, -18.039, 8.297]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.mitochondria_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[-47.734, -8.064, 14.401]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.smoothER_TT_checker_512x512_UV_GRID_0.geometry} material={materials.TT_checker_512x512_UV_GRID} position={[-27.715, -9.847, 31.128]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/3dassets/plant_cell.glb')
