/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/3dassets/dna/scene.gltf 
Author: Holoxica (https://sketchfab.com/holoxica)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dna-60e95170b37549e3b45ee490b74bb112
Title: DNA
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function DNA (props) {
  const { nodes, materials } = useGLTF('/3dassets/dna/scene.gltf')
  return (
    <group {...props} dispose={null} scale={[0.65,0.65,0.65]} position={[0,0,0]} rotation={[0.2,0.6,-0.2]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.vmd_mat_cindex_0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.vmd_mat_cindex_1} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.vmd_mat_cindex_10} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.vmd_mat_cindex_10} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.vmd_mat_cindex_5} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.vmd_mat_cindex_8} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.vmd_mat_cindex_8} />
      </group>
    </group>
  )
}

useGLTF.preload('/3dassets/dna/scene.gltf')
