/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/3dassets/voyager_space_satellite/scene.gltf 
Author: Almaz (https://sketchfab.com/Almazmeteor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/voyager-space-satellite-draft-3ae2bb2b18784eb7987ad3d46b160f02
Title: Voyager Space Satellite | Draft
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SpaceSatellite (props) {
  const { nodes, materials } = useGLTF('/3dassets/voyager_space_satellite/scene.gltf')
  return (
    <group {...props} dispose={null} scale={0.4} position={[-0.2,-1.3,0]} rotation={[0.3,3.2,0]}>
      <group rotation={[-1.844, -0.208, -0.058]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[7.46, 3.266, -0.261]} rotation={[0.001, 0.003, -0.002]} scale={0.429}>
            <mesh geometry={nodes.Object_24.geometry} material={materials.material_5} />
            <mesh geometry={nodes.Object_25.geometry} material={materials.material_0} />
          </group>
          <group position={[5.205, 4.924, -0.696]} rotation={[3.139, 1.03, -3.138]} scale={[0.165, 0.033, 0.296]}>
            <mesh geometry={nodes.Object_61.geometry} material={materials.material_5} />
            <mesh geometry={nodes.Object_62.geometry} material={materials.material_0} />
          </group>
          <group position={[0.008, 4.527, 1.68]} rotation={[-0.011, -0.018, 0]} scale={[0.154, 0.058, 0.188]}>
            <mesh geometry={nodes.Object_220.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_221.geometry} material={materials.material_0} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials.material} position={[-0.004, 2.943, -0.413]} rotation={[-0.002, -0.925, -0.003]} scale={[1.837, 0.46, 1.837]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.material_2} position={[-0.002, 4.148, -0.412]} rotation={[0.001, 0.003, -0.002]} scale={[1.647, 0.204, 1.647]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.material_2} position={[-0.001, 4.539, -0.411]} rotation={[0.001, 0.003, -0.002]} scale={[1.536, 0.217, 1.536]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.material_2} position={[0.002, 6.415, -0.41]} rotation={[0.001, 0.003, -0.002]} scale={[0.661, 0.169, 0.661]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.material_3} position={[0.003, 6.931, -0.409]} rotation={[0.001, 0.003, -0.002]} scale={[0.16, 0.292, 0.16]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.material_4} position={[-2.758, 3.813, -0.403]} rotation={[0.001, 0.003, 0.94]} scale={[0.275, 0.476, 0.275]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.material_5} position={[-6.886, 2.663, -0.382]} rotation={[0.001, 0.003, 1.552]} scale={[0.407, 1.92, 0.407]} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.material_5} position={[-2.388, 3.543, -0.405]} rotation={[0.001, 0.003, 0.94]} scale={[0.301, 0.273, 0.301]} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.material_5} position={[6.121, 3.404, -0.431]} rotation={[0.001, 0.003, -0.002]} scale={[0.631, 0.631, 0.526]} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.material_5} position={[6.752, 4.415, -0.433]} rotation={[0.001, 0.003, -0.002]} scale={[0.409, 0.224, 0.244]} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.material_5} position={[6.773, 3.261, -0.259]} rotation={[0.001, 0.003, -0.002]} scale={[0.288, 0.09, 0.288]} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.material_4} position={[7.456, 2.595, 0.342]} rotation={[1.572, -0.002, -0.003]} scale={[0.523, 0.222, 0.523]} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.material_5} position={[6.868, 4.223, -0.433]} rotation={[0.001, 0.003, -0.002]} scale={[0.104, 0.805, 0.104]} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.material} position={[1.201, 1.565, -0.341]} rotation={[-1.566, 1.226, 1.568]} scale={[0.658, 0.658, 0.046]} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.material_4} position={[0.002, 6.404, -0.41]} rotation={[0.078, 0.025, 0.366]} scale={[0.026, 1.07, 0.026]} />
          <mesh geometry={nodes.Object_37.geometry} material={materials.material_2} position={[0.004, 7.193, -0.409]} rotation={[0.001, 0.003, -0.002]} scale={[0.111, 0.202, 0.111]} />
          <mesh geometry={nodes.Object_39.geometry} material={materials.material_3} position={[0.004, 7.224, -0.409]} rotation={[0.001, 0.003, -0.002]} scale={[0.143, 0.016, 0.143]} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.material_3} position={[0.045, 2.907, 1.357]} rotation={[1.572, -0.002, -0.003]} scale={[0.307, 0.015, 0.307]} />
          <mesh geometry={nodes.Object_43.geometry} material={materials.material_4} position={[0.715, 3.691, -0.305]} rotation={[3.078, 0.271, 2.749]} scale={[0.05, 0.042, 0.05]} />
          <mesh geometry={nodes.Object_45.geometry} material={materials.material_4} position={[0.982, 3.145, -1.798]} rotation={[-0.002, -0.925, -0.003]} scale={[1.511, 0.229, 1.511]} />
          <mesh geometry={nodes.Object_47.geometry} material={materials.material_5} position={[-0.705, 3.566, -1.888]} rotation={[0.002, 0.563, -0.002]} scale={[0.077, 0.143, 0.077]} />
          <mesh geometry={nodes.Object_49.geometry} material={materials.material_3} position={[-0.001, 4.751, -0.411]} rotation={[0.001, 0.003, -0.002]} scale={[0.132, 0.361, 0.132]} />
          <mesh geometry={nodes.Object_51.geometry} material={materials.material_2} position={[0, 5.039, -0.411]} rotation={[0.001, 0.003, -0.002]} scale={[0.092, 0.25, 0.092]} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.material_4} position={[6.314, 4.419, -0.419]} rotation={[1.572, -0.002, -0.003]} scale={[0.034, 0.2, 0.029]} />
          <mesh geometry={nodes.Object_55.geometry} material={materials.material_4} position={[2.583, 3.754, -0.42]} rotation={[0.001, 0.003, -1.162]} scale={[0.036, 1.361, 0.036]} />
          <mesh geometry={nodes.Object_57.geometry} material={materials.material_5} position={[5.355, 4.426, -0.396]} rotation={[0.001, 0.003, -0.002]} scale={[0.245, 0.115, 0.107]} />
          <mesh geometry={nodes.Object_59.geometry} material={materials.material_5} position={[5.356, 4.771, -0.395]} rotation={[0.001, 0.003, -0.002]} scale={[0.305, 0.097, 0.181]} />
          <mesh geometry={nodes.Object_64.geometry} material={materials.material_5} position={[5.229, 4.943, -0.657]} rotation={[3.139, 1.03, -3.138]} scale={[0.101, 0.02, 0.249]} />
          <mesh geometry={nodes.Object_66.geometry} material={materials.material_4} position={[5.26, 4.942, -0.605]} rotation={[3.139, 1.03, -3.138]} scale={[0.051, 0.01, 0.125]} />
          <mesh geometry={nodes.Object_68.geometry} material={materials.material_4} position={[5.912, 3.207, 0.098]} rotation={[1.572, -0.002, -0.003]} scale={[0.265, 0.184, 0.265]} />
          <mesh geometry={nodes.Object_70.geometry} material={materials.material_4} position={[5.908, 3.691, 0.115]} rotation={[1.572, -0.002, -0.003]} scale={[0.094, 0.065, 0.094]} />
          <mesh geometry={nodes.Object_72.geometry} material={materials.material_6} position={[6.512, 3.667, 0.01]} rotation={[0.001, 0.003, -0.002]} scale={[0.132, 0.239, 0.112]} />
          <mesh geometry={nodes.Object_74.geometry} material={materials.material_5} position={[7.724, 2.555, -0.604]} rotation={[0.001, 0.003, -0.002]} scale={[0.285, 0.103, 0.285]} />
          <mesh geometry={nodes.Object_76.geometry} material={materials.material_0} position={[7.455, 2.82, 0.096]} rotation={[1.572, -0.002, -0.003]} scale={[0.195, 0.083, 0.195]} />
          <mesh geometry={nodes.Object_78.geometry} material={materials.material_4} position={[7.457, 2.595, 0.661]} rotation={[1.572, -0.002, -0.003]} scale={[0.192, 0.076, 0.192]} />
          <mesh geometry={nodes.Object_80.geometry} material={materials.material_5} position={[7.456, 2.617, 0.503]} rotation={[1.572, -0.002, -0.003]} scale={[0.077, 0.111, 0.077]} />
          <mesh geometry={nodes.Object_82.geometry} material={materials.material_5} position={[7.453, 2.586, -0.784]} rotation={[1.572, -0.002, -0.003]} scale={[0.331, 0.495, 0.331]} />
          <mesh geometry={nodes.Object_84.geometry} material={materials.material_5} position={[7.452, 2.587, -0.683]} rotation={[1.572, -0.002, -0.003]} scale={[0.436, 0.893, 0.435]} />
          <mesh geometry={nodes.Object_86.geometry} material={materials.material_5} position={[4.41, 3.739, -0.426]} rotation={[0.001, 0.003, -0.171]} scale={[0.157, 0.294, 0.298]} />
          <mesh geometry={nodes.Object_88.geometry} material={materials.material_5} position={[4.619, 3.665, -0.427]} rotation={[0.001, 0.003, -1.742]} scale={[0.139, 0.148, 0.139]} />
          <mesh geometry={nodes.Object_90.geometry} material={materials.material_5} position={[-1.47, 3.674, -0.79]} rotation={[-2.393, -0.001, -3.138]} scale={[-0.036, 0.618, 0.036]} />
          <mesh geometry={nodes.Object_92.geometry} material={materials.material_5} position={[-8.105, 2.665, -0.378]} rotation={[2.264, -0.003, -0.001]} scale={[0.514, 0.055, 0.018]} />
          <mesh geometry={nodes.Object_94.geometry} material={materials.material_5} position={[-1.785, 3.352, -0.407]} rotation={[0.001, 0.003, -0.002]} scale={[0.308, 0.242, 0.278]} />
          <mesh geometry={nodes.Object_96.geometry} material={materials.material} position={[-2.244, 4.171, -0.405]} rotation={[-0.031, -0.324, -0.104]} scale={[1.419, 1.005, 1.057]} />
          <mesh geometry={nodes.Object_98.geometry} material={materials.material_5} position={[-3.033, 4.115, -0.852]} rotation={[0.001, 0.003, 0.176]} scale={[0.219, 0.122, 0.17]} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.material_4} position={[-2.912, 3.679, -0.922]} rotation={[2.161, 0.839, -1.361]} scale={[-0.033, 0.376, 0.033]} />
          <mesh geometry={nodes.Object_102.geometry} material={materials.material_6} position={[1.318, 1.177, -0.342]} rotation={[-1.566, 1.226, 1.568]} scale={[0.523, 0.02, 0.039]} />
          <mesh geometry={nodes.Object_104.geometry} material={materials.material_4} position={[4.04, 4.673, -0.414]} rotation={[-0.104, -0.836, 0.666]} scale={[0.02, 0.137, 0.02]} />
          <mesh geometry={nodes.Object_106.geometry} material={materials.material_5} position={[4.619, 4.052, -0.56]} rotation={[-2.647, -0.676, 0.545]} scale={[0.022, 0.159, 0.022]} />
          <mesh geometry={nodes.Object_108.geometry} material={materials.material_5} position={[6.869, 4.845, -0.433]} rotation={[0.001, 0.003, -0.002]} scale={[0.119, 0.055, 0.119]} />
          <mesh geometry={nodes.Object_110.geometry} material={materials.material_4} position={[7.457, 2.597, -0.231]} rotation={[1.575, -0.322, -0.005]} scale={[0.505, 0.315, 0.486]} />
          <mesh geometry={nodes.Object_112.geometry} material={materials.material_4} position={[-4.024, 3.321, -0.758]} rotation={[0.001, 0.003, -0.002]} scale={[0.063, 0.071, 0.095]} />
          <mesh geometry={nodes.Object_114.geometry} material={materials.material_4} position={[-4.722, -0.409, 2.998]} rotation={[-0.453, 0.458, -0.577]} scale={[0.033, 6.138, 0.033]} />
          <mesh geometry={nodes.Object_116.geometry} material={materials.material_4} position={[-3.333, 4.141, -0.419]} rotation={[1.49, -0.629, 1.839]} scale={[0.016, 0.33, 0.016]} />
          <mesh geometry={nodes.Object_118.geometry} material={materials['3.001']} position={[7.456, 2.595, 0.342]} rotation={[1.572, -0.002, -0.003]} scale={[0.523, 0.222, 0.523]} />
          <mesh geometry={nodes.Object_120.geometry} material={materials.material_3} position={[0.002, 6.415, -0.41]} rotation={[0.001, 0.003, -0.002]} scale={[0.671, 0.172, 0.671]} />
          <mesh geometry={nodes.Object_122.geometry} material={materials.material_5} position={[-3.013, 3.998, -0.852]} rotation={[0.001, 0.003, 0.176]} scale={[0.237, 0.014, 0.184]} />
          <mesh geometry={nodes.Object_124.geometry} material={materials.material_5} position={[0.003, 3.789, 1.487]} rotation={[0.468, 0.002, -0.003]} scale={[0.039, 0.647, 0.039]} />
          <mesh geometry={nodes.Object_126.geometry} material={materials.material} position={[0.003, 3.789, 1.487]} rotation={[0.468, 0.002, -0.003]} scale={[0.039, 0.647, 0.039]} />
          <mesh geometry={nodes.Object_128.geometry} material={materials.material_5} position={[-1.48, 2.322, -0.544]} rotation={[0.002, 0.004, -0.004]} scale={[0.082, 0.172, 0.259]} />
          <mesh geometry={nodes.Object_130.geometry} material={materials.material_4} position={[3.692, 4.198, -0.415]} rotation={[0.002, 0.004, -0.8]} scale={[0.031, 0.041, 0.041]} />
          <mesh geometry={nodes.Object_132.geometry} material={materials.material_2} position={[2.245, 4.429, -0.126]} rotation={[0.004, 0.454, -0.004]} scale={[0.195, 0.195, 0.037]} />
          <mesh geometry={nodes.Object_134.geometry} material={materials.material} position={[2.462, 4.257, -0.232]} rotation={[0.002, 0.004, -0.004]} scale={[0.06, 0.036, 0.036]} />
          <mesh geometry={nodes.Object_136.geometry} material={materials.material} position={[2.46, 4.258, -0.579]} rotation={[-3.14, -0.004, -3.138]} scale={[-0.06, 0.036, 0.036]} />
          <mesh geometry={nodes.Object_138.geometry} material={materials.material_5} position={[1.025, 2.75, 0.973]} rotation={[0.005, 0.654, -0.005]} scale={[0.529, 0.199, 0.112]} />
          <mesh geometry={nodes.Object_140.geometry} material={materials.material_5} position={[-1.576, 3.355, -1.235]} rotation={[1.633, -0.932, 0.867]} scale={[-0.03, 0.03, 0.03]} />
          <mesh geometry={nodes.Object_142.geometry} material={materials.material_3} position={[-3.231, 4.086, -0.853]} rotation={[0.002, 0.004, -1.402]} scale={0.071} />
          <mesh geometry={nodes.Object_144.geometry} material={materials.material} position={[1.707, 3.924, 0.201]} rotation={[2.1, 0.695, -2.34]} scale={[0.037, 0.591, 0.037]} />
          <mesh geometry={nodes.Object_146.geometry} material={materials.material_4} position={[1.308, 3.395, -1.268]} rotation={[-2.783, 0.204, -2.635]} scale={[-0.04, 0.04, 0.04]} />
          <mesh geometry={nodes.Object_148.geometry} material={materials.material_2} position={[-2.217, 4.171, -0.244]} rotation={[1.573, -0.004, -0.004]} scale={0.063} />
          <mesh geometry={nodes.Object_150.geometry} material={materials.material_0} position={[-2.849, 4.034, -0.78]} rotation={[-2.981, 0.837, 2.511]} scale={[0.022, 0.161, 0.022]} />
          <mesh geometry={nodes.Object_152.geometry} material={materials.material_4} position={[1.703, 3.926, -1.008]} rotation={[1.051, 0.699, -0.81]} scale={[-0.019, 0.68, 0.019]} />
          <mesh geometry={nodes.Object_154.geometry} material={materials['Material.001']} position={[5.981, 3.158, -0.453]} rotation={[1.572, -0.002, -0.003]} scale={[0.994, 0.691, 0.994]} />
          <mesh geometry={nodes.Object_156.geometry} material={materials.material} position={[-0.553, 1.785, 0.684]} rotation={[-0.598, 0.004, 0]} scale={[0.231, 0.027, 0.027]} />
          <mesh geometry={nodes.Object_158.geometry} material={materials.material_4} position={[1.216, 1.57, -0.341]} rotation={[-1.566, 1.226, 1.568]} scale={[0.605, 0.605, 0.042]} />
          <mesh geometry={nodes.Object_160.geometry} material={materials.material_4} position={[-2.883, 3.551, -0.391]} rotation={[0.004, -0.003, 0.002]} scale={[0.023, 0.023, 0.066]} />
          <mesh geometry={nodes.Object_162.geometry} material={materials.material} position={[0.624, 2.445, -0.348]} rotation={[0.004, -0.003, 0.002]} scale={0.346} />
          <mesh geometry={nodes.Object_164.geometry} material={materials.material_5} position={[4.281, 4.592, -0.578]} rotation={[0.004, -0.003, 0.002]} scale={[-0.05, 0.038, 0.038]} />
          <mesh geometry={nodes.Object_166.geometry} material={materials.material_5} position={[4.959, 4.209, -0.544]} rotation={[0.004, -0.003, 0.002]} scale={0.033} />
          <mesh geometry={nodes.Object_168.geometry} material={materials.material_5} position={[4.545, 4.051, -0.252]} rotation={[0.004, 0.173, -0.204]} scale={[0.188, 0.092, 0.062]} />
          <mesh geometry={nodes.Object_170.geometry} material={materials.material_4} position={[-3.067, 2.741, -0.357]} rotation={[0.004, -0.003, 1.455]} scale={[0.017, 1.901, 0.017]} />
          <mesh geometry={nodes.Object_172.geometry} material={materials.material_4} position={[-1.838, 2.607, -0.338]} rotation={[0.258, 0.366, 0.831]} scale={[0.017, 0.727, 0.017]} />
          <mesh geometry={nodes.Object_174.geometry} material={materials.material_3} position={[5, 3.633, -0.428]} rotation={[0.004, -0.003, 2.928]} scale={[-0.033, 0.094, 0.033]} />
          <mesh geometry={nodes.Object_176.geometry} material={materials.material_6} position={[1.19, 1.025, -0.571]} rotation={[-0.296, 0.485, -0.988]} scale={[0.03, 0.342, 0.03]} />
          <mesh geometry={nodes.Object_178.geometry} material={materials.material_4} position={[2.764, 3.803, -0.421]} rotation={[0.001, 0.003, -1.162]} scale={[0.045, 0.081, 0.045]} />
          <mesh geometry={nodes.Object_180.geometry} material={materials.material_4} position={[1.836, 3.403, -0.419]} rotation={[0.001, 0.003, -1.162]} scale={[0.048, 0.086, 0.048]} />
          <mesh geometry={nodes.Object_182.geometry} material={materials.material} position={[1.771, 3.857, 0.174]} rotation={[2.1, 0.695, -2.34]} scale={[0.04, 0.64, 0.04]} />
          <mesh geometry={nodes.Object_184.geometry} material={materials.material_4} position={[-4.891, 2.615, -0.716]} rotation={[-2.735, 0.123, -2.169]} scale={[-0.025, 0.05, 0.025]} />
          <mesh geometry={nodes.Object_186.geometry} material={materials.material_4} position={[2.086, 4.314, -0.337]} rotation={[-0.365, 0.492, -0.663]} scale={[0.017, 0.023, 0.017]} />
          <mesh geometry={nodes.Object_188.geometry} material={materials.material} position={[4.493, 4.323, -0.345]} rotation={[0.004, -0.003, -1.569]} scale={[0.021, 2.026, 0.021]} />
          <mesh geometry={nodes.Object_190.geometry} material={materials.material_5} position={[2.301, 4.337, -0.351]} rotation={[0.004, -0.003, -1.683]} scale={[0.029, 0.075, 0.029]} />
          <mesh geometry={nodes.Object_192.geometry} material={materials.material_4} position={[-1.064, 2.951, -1.835]} rotation={[-0.001, -0.307, -0.002]} scale={[1.511, 0.21, 1.511]} />
          <mesh geometry={nodes.Object_194.geometry} material={materials.material_4} position={[-1.036, 2.952, 1.03]} rotation={[-3.141, -0.344, -3.139]} scale={[-1.511, 0.21, 1.511]} />
          <mesh geometry={nodes.Object_196.geometry} material={materials.material_4} position={[1.064, 2.948, 1.01]} rotation={[3.141, 0.32, -3.139]} scale={[1.511, 0.21, 1.511]} />
          <mesh geometry={nodes.Object_198.geometry} material={materials.material_4} position={[1.703, 3.926, -1.008]} rotation={[1.051, 0.699, -0.81]} scale={[-0.019, 0.68, 0.019]} />
          <mesh geometry={nodes.Object_200.geometry} material={materials.material_4} position={[1.308, 3.395, -1.268]} rotation={[-2.783, 0.204, -2.635]} scale={[-0.04, 0.04, 0.04]} />
          <mesh geometry={nodes.Object_202.geometry} material={materials.material_4} position={[1.308, 3.395, -1.268]} rotation={[-2.783, 0.204, -2.635]} scale={[-0.04, 0.04, 0.04]} />
          <mesh geometry={nodes.Object_204.geometry} material={materials.material_2} position={[2.234, 4.425, -0.677]} rotation={[3.138, 0.414, -3.138]} scale={[-0.195, 0.195, 0.037]} />
          <mesh geometry={nodes.Object_206.geometry} material={materials.material} position={[1.683, 3.919, -0.982]} rotation={[1.072, 0.715, -0.848]} scale={[-0.037, 0.591, 0.037]} />
          <mesh geometry={nodes.Object_208.geometry} material={materials.material_4} position={[1.343, 3.391, 0.502]} rotation={[-0.362, 0.242, -0.492]} scale={0.04} />
          <mesh geometry={nodes.Object_210.geometry} material={materials.material_4} position={[1.727, 3.922, 0.226]} rotation={[2.119, 0.678, -2.376]} scale={[0.019, 0.68, 0.019]} />
          <mesh geometry={nodes.Object_212.geometry} material={materials.material_4} position={[1.343, 3.391, 0.502]} rotation={[-0.362, 0.242, -0.492]} scale={0.04} />
          <mesh geometry={nodes.Object_214.geometry} material={materials.material} position={[1.585, 3.177, 0.503]} rotation={[0, -0.3, 0]} scale={[0.131, 0.206, 0.114]} />
          <mesh geometry={nodes.Object_216.geometry} material={materials.material} position={[0.008, 4.404, 1.706]} rotation={[-0.001, -0.018, 0]} scale={[0.201, 0.031, 0.176]} />
          <mesh geometry={nodes.Object_218.geometry} material={materials.material_4} position={[0.008, 4.364, 1.694]} rotation={[-0.001, -0.018, 0]} scale={[0.163, 0.007, 0.176]} />
          <mesh geometry={nodes.Object_223.geometry} material={materials.material} position={[1.008, 3.568, -1.827]} rotation={[0, -0.617, 0]} scale={[0.277, 0.149, 0.018]} />
          <mesh geometry={nodes.Object_225.geometry} material={materials.material_4} position={[0.006, 4.355, 1.813]} rotation={[-0.001, -0.018, 0]} scale={[0.171, 0.005, 0.009]} />
          <mesh geometry={nodes.Object_227.geometry} material={materials.material} position={[-1.014, 3.436, -1.587]} rotation={[0, 0.574, 0]} scale={[0.063, 0.074, 0.128]} />
          <mesh geometry={nodes.Object_229.geometry} material={materials.material} position={[0.83, 3.426, -1.919]} rotation={[0, -0.617, 0]} scale={0.014} />
          <mesh geometry={nodes.Object_231.geometry} material={materials.material} position={[-0.081, 4.444, 1.655]} rotation={[-0.011, -0.018, 0]} scale={[0.013, 0.022, 0.182]} />
          <mesh geometry={nodes.Object_233.geometry} material={materials.material} position={[1.152, 3.426, -1.69]} rotation={[0, -0.617, 0]} scale={0.014} />
          <mesh geometry={nodes.Object_235.geometry} material={materials.material_4} position={[0.004, 4.583, 1.878]} rotation={[-0.056, -0.018, -0.001]} scale={[0.018, 0.098, 0.006]} />
          <mesh geometry={nodes.Object_237.geometry} material={materials.material_4} position={[0.005, 4.63, 1.824]} rotation={[-0.446, -0.016, -0.008]} scale={[0.035, 0.004, 0.021]} />
          <mesh geometry={nodes.Object_239.geometry} material={materials.material} position={[1.851, 3.177, -0.434]} rotation={[0, 0.008, 0]} scale={[0.131, 0.206, 0.114]} />
          <mesh geometry={nodes.Object_241.geometry} material={materials.material_4} position={[0.144, 4.348, 1.612]} rotation={[-0.001, -0.018, 0]} scale={[0.015, 0.013, 0.02]} />
          <mesh geometry={nodes.Object_243.geometry} material={materials.material_3} position={[0.008, 4.319, 1.88]} rotation={[0.285, -0.017, 0.005]} scale={[0.015, 0.02, 0.016]} />
          <mesh geometry={nodes.Object_245.geometry} material={materials.material_3} position={[0.008, 4.299, 1.874]} rotation={[0.285, -0.017, 0.005]} scale={[0.026, 0.005, 0.018]} />
          <mesh geometry={nodes.Object_247.geometry} material={materials.material} position={[1.585, 3.177, -1.373]} rotation={[0, 0.201, 0]} scale={[0.131, 0.206, 0.114]} />
          <mesh geometry={nodes.Object_249.geometry} material={materials.material_3} position={[2.112, 4.504, -0.053]} rotation={[0, 0.152, 0]} scale={[0.039, 0.032, 0.011]} />
          <mesh geometry={nodes.Object_251.geometry} material={materials.material_3} position={[2.302, 4.532, -0.657]} rotation={[-Math.PI, 0.546, -Math.PI]} scale={[-0.046, 0.042, 0.019]} />
          <mesh geometry={nodes.Object_253.geometry} material={materials.material_4} position={[2.098, 4.581, -0.771]} rotation={[-1.971, 1.111, 2.003]} scale={[-0.048, 0.006, 0.026]} />
          <mesh geometry={nodes.Object_255.geometry} material={materials['1.001']} position={[0.32, 3.233, -2.165]} rotation={[Math.PI / 2, 0, -0.02]} scale={[0.053, 0.019, 0.053]} />
          <mesh geometry={nodes.Object_257.geometry} material={materials.material_4} position={[1.109, 3.424, -1.628]} rotation={[Math.PI / 2, 0, 0.617]} scale={[0.01, 0.086, 0.008]} />
          <mesh geometry={nodes.Object_259.geometry} material={materials.material_6} position={[-0.019, 4.418, 2.005]} rotation={[-1.766, 0.003, -0.018]} scale={[0.01, 0.205, 0.01]} />
          <mesh geometry={nodes.Object_261.geometry} material={materials.material_4} position={[0, 3.394, 1.278]} rotation={[0, -0.018, 0]} scale={[0.047, 0.019, 0.047]} />
          <mesh geometry={nodes.Object_263.geometry} material={materials.material} position={[-0.033, 4.454, 1.856]} rotation={[1.56, 0, 0.018]} scale={[0.023, 0.054, 0.023]} />
          <mesh geometry={nodes.Object_265.geometry} material={materials.material_4} position={[0.786, 3.424, -1.857]} rotation={[Math.PI / 2, 0, 0.617]} scale={[0.01, 0.086, 0.008]} />
          <mesh geometry={nodes.Object_267.geometry} material={materials.material_3} position={[1.713, 3.326, 0.497]} rotation={[Math.PI / 2, 0, -1.211]} scale={[0.037, 0.02, 0.037]} />
          <mesh geometry={nodes.Object_269.geometry} material={materials.material_3} position={[1.752, 3.326, 0.512]} rotation={[Math.PI / 2, 0, -1.211]} scale={[0.022, 0.032, 0.022]} />
          <mesh geometry={nodes.Object_271.geometry} material={materials.material} position={[-0.526, 6.635, -0.409]} rotation={[0, 0.02, 0]} scale={0.035} />
          <mesh geometry={nodes.Object_273.geometry} material={materials.material_6} position={[0.445, 6.546, -0.855]} rotation={[0, 0.02, 0]} scale={[0.014, 2.202, 0.014]} />
          <mesh geometry={nodes.Object_275.geometry} material={materials.material_4} position={[1.019, 3.142, -1.862]} rotation={[0, -1.438, 0]} scale={[0.007, 0.409, 0.007]} />
          <mesh geometry={nodes.Object_277.geometry} material={materials.material_4} position={[0.534, 6.307, -0.787]} rotation={[-0.121, -0.087, 0.539]} scale={[0.024, 0.013, 0.024]} />
          <mesh geometry={nodes.Object_279.geometry} material={materials.material_6} position={[0.423, 6.512, 0.059]} rotation={[-2.999, -0.02, -3.139]} scale={[-0.014, 2.202, 0.014]} />
          <mesh geometry={nodes.Object_281.geometry} material={materials.material_3} position={[0.667, 2.144, -0.449]} rotation={[-Math.PI, -1.211, 0]} scale={[0.065, 0.035, 0.065]} />
          <mesh geometry={nodes.Object_283.geometry} material={materials.material_3} position={[-1.421, 2.375, -0.645]} rotation={[1.242, -0.26, -1.368]} scale={[-0.029, 0.054, 0.029]} />
          <mesh geometry={nodes.Object_285.geometry} material={materials.material_4} position={[2.044, 4.395, -0.769]} rotation={[-2.802, 0.097, -2.523]} scale={[-0.048, 0.036, 0.048]} />
          <mesh geometry={nodes.Object_287.geometry} material={materials.material_6} position={[2.1, 4.493, -0.752]} rotation={[Math.PI / 2, 0, 3.122]} scale={[-0.013, 0.013, 0.013]} />
          <mesh geometry={nodes.Object_289.geometry} material={materials.material_4} position={[-2.912, 3.679, -0.922]} rotation={[2.161, 0.839, -1.361]} scale={[-0.033, 0.376, 0.033]} />
          <mesh geometry={nodes.Object_291.geometry} material={materials.material_4} position={[-2.912, 3.679, 0.153]} rotation={[0.981, 0.839, -1.781]} scale={[0.033, 0.376, 0.033]} />
          <mesh geometry={nodes.Object_293.geometry} material={materials.material_4} position={[-4.896, 2.611, -0.714]} rotation={[-2.688, 0.367, -2.298]} scale={[-0.025, 0.05, 0.025]} />
          <mesh geometry={nodes.Object_295.geometry} material={materials.material_4} position={[-2.912, 3.679, -0.922]} rotation={[2.161, 0.839, -1.361]} scale={[-0.033, 0.376, 0.033]} />
          <mesh geometry={nodes.Object_297.geometry} material={materials.material_4} position={[-3.528, 3.305, -0.071]} rotation={[0.981, 0.839, -1.781]} scale={[0.033, 0.376, 0.033]} />
          <mesh geometry={nodes.Object_299.geometry} material={materials.material_4} position={[-4.899, 2.657, -0.035]} rotation={[-2.822, -0.178, -2.089]} scale={[-0.025, 0.05, 0.025]} />
          <mesh geometry={nodes.Object_301.geometry} material={materials.material_4} position={[-4.881, 2.977, -0.403]} rotation={[-2.638, 0.261, -2.187]} scale={[-0.025, 0.05, 0.025]} />
          <mesh geometry={nodes.Object_303.geometry} material={materials.material_5} position={[-7.323, 2.672, -0.377]} rotation={[0.001, 0.003, 1.552]} scale={[0.407, 1.92, 0.407]} />
          <mesh geometry={nodes.Object_305.geometry} material={materials.material_5} position={[-7.254, 2.665, -0.38]} rotation={[2.264, -0.003, -0.001]} scale={[0.514, 0.055, 0.018]} />
          <mesh geometry={nodes.Object_307.geometry} material={materials.material_5} position={[0.004, 1.85, -0.365]} rotation={[0.001, 0.003, 1.552]} scale={[0.439, 1.795, 0.439]} />
          <mesh geometry={nodes.Object_309.geometry} material={materials.material_4} position={[-3.087, 3.527, 0.354]} rotation={[0.001, 0.003, 3.14]} scale={[0.063, 0.071, 0.118]} />
          <mesh geometry={nodes.Object_311.geometry} material={materials.material_4} position={[-3.087, 3.527, -1.132]} rotation={[3.141, 0.003, 0.002]} scale={[-0.063, 0.071, 0.118]} />
          <mesh geometry={nodes.Object_313.geometry} material={materials.material_5} position={[-8.105, 2.665, -0.378]} rotation={[2.264, -0.003, -0.001]} scale={[0.514, 0.055, 0.018]} />
          <mesh geometry={nodes.Object_315.geometry} material={materials.material_5} position={[5.355, 4.676, -0.396]} rotation={[0.001, 0.003, -0.002]} scale={[0.245, 0.115, 0.107]} />
          <mesh geometry={nodes.Object_317.geometry} material={materials.material_4} position={[-4.012, 3.216, -0.398]} scale={[0.017, 0.146, 0.218]} />
          <mesh geometry={nodes.Object_319.geometry} material={materials.material_5} position={[-13.361, 11.774, -0.351]} rotation={[0.937, -0.285, -0.311]} scale={[0.185, 0.145, 0.15]} />
          <mesh geometry={nodes.Object_321.geometry} material={materials.material_5} position={[-8.474, 8.219, -0.197]} rotation={[1.079, -0.486, -0.347]} scale={[0.185, 0.145, 0.15]} />
          <mesh geometry={nodes.Object_323.geometry} material={materials.material_3} position={[-8.479, 8.21, -0.192]} rotation={[1.079, -0.486, -0.347]} scale={[0.185, 0.129, 0.15]} />
          <mesh geometry={nodes.Object_325.geometry} material={materials.material_3} position={[-13.363, 11.769, -0.347]} rotation={[0.937, -0.285, -0.311]} scale={[0.185, 0.129, 0.15]} />
          <mesh geometry={nodes.Object_327.geometry} material={materials.material_4} position={[-3.063, 3.552, 0.305]} rotation={[-0.744, -0.053, -0.378]} scale={[0.021, 0.043, 0.021]} />
          <mesh geometry={nodes.Object_329.geometry} material={materials.material_4} position={[-5.614, 3.328, -0.391]} scale={[1.752, 0.023, 0.045]} />
          <mesh geometry={nodes.Object_331.geometry} material={materials.material_10} position={[-7.508, 2.936, 0.005]} scale={[0.039, 0.028, 0.034]} />
          <mesh geometry={nodes.Object_333.geometry} material={materials.material_4} position={[-7.511, 2.414, 0.008]} scale={[0.05, 0.052, 0.043]} />
          <mesh geometry={nodes.Object_335.geometry} material={materials.material} position={[-7.401, 2.401, -0.023]} rotation={[-0.689, 0, 0]} scale={[0.113, 0.022, 0.007]} />
          <mesh geometry={nodes.Object_337.geometry} material={materials.material_4} position={[-3.086, 3.528, 0.288]} rotation={[-1.395, -0.047, -0.227]} scale={[0.021, 0.043, 0.021]} />
          <mesh geometry={nodes.Object_339.geometry} material={materials.material_4} position={[-3.023, 3.535, 0.291]} rotation={[-0.484, 0.529, -1.224]} scale={[0.021, 0.043, 0.021]} />
          <mesh geometry={nodes.Object_341.geometry} material={materials.material_4} position={[-3.088, 3.561, -1.074]} rotation={[-2.158, -0.195, -2.597]} scale={[-0.023, 0.045, 0.023]} />
          <mesh geometry={nodes.Object_343.geometry} material={materials.material_4} position={[-3.177, 3.509, -1.071]} rotation={[-3.138, -0.642, 2.989]} scale={[-0.024, 0.016, 0.016]} />
          <mesh geometry={nodes.Object_345.geometry} material={materials.material_4} position={[-3.09, 3.528, -1.063]} rotation={[-1.746, -0.047, -2.819]} scale={[-0.025, 0.049, 0.025]} />
          <mesh geometry={nodes.Object_347.geometry} material={materials.material_4} position={[-3.041, 3.535, -1.078]} rotation={[-2.682, 0.435, -1.863]} scale={[-0.021, 0.043, 0.021]} />
          <mesh geometry={nodes.Object_349.geometry} material={materials.material_4} position={[-7.511, 2.414, -0.74]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.05, 0.052, 0.043]} />
          <mesh geometry={nodes.Object_351.geometry} material={materials.material_10} position={[-7.791, 1.567, -0.361]} scale={[0.02, 0.034, 0.044]} />
          <mesh geometry={nodes.Object_353.geometry} material={materials.material_3} position={[5.555, 4.842, -0.654]} rotation={[Math.PI / 2, 0, 0.479]} scale={[0.123, 0.097, 0.123]} />
          <mesh geometry={nodes.Object_355.geometry} material={materials.material_3} position={[5.619, 4.842, -0.776]} rotation={[Math.PI / 2, 0, 0.479]} scale={[0.124, 0.039, 0.124]} />
          <mesh geometry={nodes.Object_357.geometry} material={materials.material_3} position={[5.607, 4.842, -0.753]} rotation={[Math.PI / 2, 0, 0.479]} scale={[0.131, 0.016, 0.131]} />
          <mesh geometry={nodes.Object_359.geometry} material={materials.material_10} position={[-5.614, 3.346, -0.391]} rotation={[0, 0, -Math.PI / 2]} scale={[0.021, 1.773, 0.021]} />
          <mesh geometry={nodes.Object_361.geometry} material={materials.material_6} position={[-8.58, 8.108, -0.492]} rotation={[1.079, -0.486, -0.347]} scale={[0.033, 0.159, 0.033]} />
          <mesh geometry={nodes.Object_363.geometry} material={materials.material_6} position={[-13.462, 11.6, -0.615]} rotation={[0.937, -0.285, -0.311]} scale={[0.033, 0.159, 0.033]} />
          <mesh geometry={nodes.Object_365.geometry} material={materials.material_6} position={[-9.085, 2.666, -0.368]} rotation={[0, 0.02, -Math.PI / 2]} scale={[0.694, 0.047, 0.694]} />
          <mesh geometry={nodes.Object_367.geometry} material={materials.material} position={[-9.079, 2.666, -0.368]} rotation={[3.139, -0.02, -1.571]} scale={[0.704, 0.049, 0.704]} />
          <mesh geometry={nodes.Object_369.geometry} material={materials.material_4} position={[-9.049, 2.666, -0.368]} rotation={[0.864, 0.438, 1.922]} scale={[-0.015, 0.377, 0.015]} />
          <mesh geometry={nodes.Object_371.geometry} material={materials.material_4} position={[-6.893, 3.346, -0.391]} rotation={[0, 0, -Math.PI / 2]} scale={[0.034, 0.012, 0.034]} />
          <mesh geometry={nodes.Object_373.geometry} material={materials.material_4} position={[-3.933, 2.74, -0.496]} rotation={[0.628, 0.334, -1.081]} scale={[0.024, 0.042, 0.024]} />
          <mesh geometry={nodes.Object_375.geometry} material={materials.material_4} position={[-4.014, 3.319, -0.648]} rotation={[2.514, 0.334, -2.06]} scale={[-0.024, 0.042, 0.024]} />
          <mesh geometry={nodes.Object_377.geometry} material={materials.material_4} position={[-3.933, 2.74, -0.496]} rotation={[0.628, 0.334, -1.081]} scale={[0.024, 0.042, 0.024]} />
          <mesh geometry={nodes.Object_379.geometry} material={materials.material_4} position={[-3.978, 3.166, -0.389]} rotation={[2.7, 0.487, -2.193]} scale={[-0.03, 0.051, 0.03]} />
          <mesh geometry={nodes.Object_381.geometry} material={materials['1.001']} position={[-7.502, 2.663, -0.382]} rotation={[0, 0, -Math.PI / 2]} scale={[0.298, 0.343, 0.298]} />
          <mesh geometry={nodes.Object_383.geometry} material={materials.material} position={[-7.511, 2.663, 0.003]} scale={[0.032, 0.251, 0.028]} />
          <mesh geometry={nodes.Object_385.geometry} material={materials.material_3} position={[-7.578, 2.872, 0.007]} rotation={[-0.559, 0, -Math.PI / 2]} scale={[0.018, 0.088, 0.018]} />
          <mesh geometry={nodes.Object_387.geometry} material={materials.material} position={[-7.511, 2.422, 0.039]} rotation={[Math.PI / 2, 0, 0]} scale={[0.023, 0.02, 0.02]} />
          <mesh geometry={nodes.Object_389.geometry} material={materials.material_5} position={[-7.319, 2.405, -0.021]} rotation={[0.965, 0, 0]} scale={[0.016, 0.014, 0.014]} />
          <mesh geometry={nodes.Object_391.geometry} material={materials.material_3} position={[-7.419, 3.034, -0.021]} rotation={[0, 0, -Math.PI / 2]} scale={[0.028, 0.136, 0.028]} />
          <mesh geometry={nodes.Object_393.geometry} material={materials.material_3} position={[-7.278, 3.034, -0.021]} rotation={[0, 0, -Math.PI / 2]} scale={[0.023, 0.047, 0.023]} />
          <mesh geometry={nodes.Object_395.geometry} material={materials.material_3} position={[-7.589, 3.034, -0.021]} rotation={[0, 0, -Math.PI / 2]} scale={[0.016, 0.033, 0.016]} />
          <mesh geometry={nodes.Object_397.geometry} material={materials.material_3} position={[-7.375, 3.034, -0.021]} rotation={[0, 0, -Math.PI / 2]} scale={[0.031, 0.017, 0.031]} />
          <mesh geometry={nodes.Object_399.geometry} material={materials.material_3} position={[-7.32, 3.034, -0.021]} rotation={[0, 0, -Math.PI / 2]} scale={[0.032, 0.008, 0.032]} />
          <mesh geometry={nodes.Object_401.geometry} material={materials.material_5} position={[-7.641, 2.875, 0.026]} rotation={[1.247, 0, 0]} scale={[0.012, 0.01, 0.01]} />
          <mesh geometry={nodes.Object_403.geometry} material={materials.material} position={[-7.231, 3.034, -0.021]} rotation={[0, 0, -Math.PI / 2]} scale={[0.015, 0.057, 0.015]} />
          <mesh geometry={nodes.Object_405.geometry} material={materials.material_4} position={[-3.087, 3.527, 0.356]} rotation={[Math.PI / 2, 0, 0]} scale={[0.036, 0.035, 0.036]} />
          <mesh geometry={nodes.Object_407.geometry} material={materials.material_0} position={[-3.087, 3.527, 0.363]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-0.036, 0.028, 0.036]} />
          <mesh geometry={nodes.Object_409.geometry} material={materials.material_4} position={[-3.087, 3.527, -1.135]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-0.036, 0.035, 0.036]} />
          <mesh geometry={nodes.Object_411.geometry} material={materials.material_5} position={[-7.511, 2.422, -0.772]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-0.023, 0.02, 0.02]} />
          <mesh geometry={nodes.Object_413.geometry} material={materials.material_5} position={[-7.789, 2.414, 0.001]} rotation={[0, 0, -Math.PI / 2]} scale={[0.028, 0.03, 0.028]} />
          <mesh geometry={nodes.Object_415.geometry} material={materials.material_0} position={[-7.789, 2.414, -0.739]} rotation={[0, 0, -Math.PI / 2]} scale={[0.028, 0.03, 0.028]} />
          <mesh geometry={nodes.Object_417.geometry} material={materials.material_10} position={[-7.759, 1.966, -0.113]} rotation={[-2.86, 0.014, -3.061]} scale={[-0.016, 0.445, 0.015]} />
          <mesh geometry={nodes.Object_419.geometry} material={materials.material_10} position={[-7.759, 1.966, -0.813]} rotation={[-2.974, 0.014, -3.061]} scale={[-0.016, 0.445, 0.015]} />
          <mesh geometry={nodes.Object_421.geometry} material={materials.material_10} position={[-6.494, 1.951, -0.609]} rotation={[-0.265, 0.098, -0.379]} scale={[0.016, 0.45, 0.015]} />
          <mesh geometry={nodes.Object_423.geometry} material={materials.material_10} position={[-6.589, 1.845, -0.011]} rotation={[-1.62, -1.289, -1.537]} scale={[-0.025, 0.721, 0.026]} />
          <mesh geometry={nodes.Object_425.geometry} material={materials.material_10} position={[-7.449, 1.845, -0.735]} rotation={[-1.522, 1.289, 1.604]} scale={[-0.025, 0.721, 0.026]} />
          <mesh geometry={nodes.Object_427.geometry} material={materials.material_3} position={[2.102, 4.499, -0.742]} rotation={[-Math.PI, 0.152, -Math.PI]} scale={[-0.039, 0.032, 0.011]} />
          <mesh geometry={nodes.Object_429.geometry} material={materials.material_5} position={[-0.006, 2.426, 1.214]} rotation={[0.001, 0.003, 1.552]} scale={[0.455, 1.86, 0.455]} />
          <mesh geometry={nodes.Object_431.geometry} material={materials.material_3} position={[-0.13, 2.442, 1.354]} rotation={[1.571, 1.549, 0.084]} scale={[0.022, 0.032, 0.022]} />
          <mesh geometry={nodes.Object_433.geometry} material={materials.material_10} position={[8.176, 2.698, 0.046]} scale={[0.148, 0.039, 0.143]} />
          <mesh geometry={nodes.Object_435.geometry} material={materials.material_5} position={[4.045, 4.893, -0.515]} rotation={[-0.152, 0, 0]} scale={[-0.228, 0.144, 0.2]} />
          <mesh geometry={nodes.Object_437.geometry} material={materials['Material.001']} rotation={[-2.908, -0.078, 2.438]} scale={0.125} />
          <mesh geometry={nodes.Object_439.geometry} material={materials['Material.004']} rotation={[2.677, -0.165, 1.606]} scale={0.125} />
          <mesh geometry={nodes.Object_441.geometry} material={materials['Material.004']} rotation={[2.173, 0.411, 2.742]} scale={0.202} />
          <mesh geometry={nodes.Object_443.geometry} material={materials['Material.004']} rotation={[1.069, 0.906, 3.034]} scale={0.125} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3dassets/voyager_space_saellite/scene.gltf')
