/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/3dassets/human_brain.glb 
Author: FrankJohansson (https://sketchfab.com/pranktoy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-brain-cerebrum-brainstem-0aa0e33c5c854d1bab7bac9e1c7acaec
Title: Human brain, Cerebrum & Brainstem
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function HumanBrain (props) {
  const { nodes, materials } = useGLTF('/3dassets/human_brain.glb')
  return (
    <group {...props} dispose={null} scale={[1.3,1.3,1.3]} position={[0.05,-0.02,0]} rotation={[0,5.6,0]}>
      <group position={[-0.039, 0, 0.016]} rotation={[-Math.PI / 2, 0, -0.889]} scale={0.093}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Hj__rna3_1} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3dassets/human_brain.glb')
