/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/orange_spaceship.glb 
Author: blacknibow (https://sketchfab.com/blacknibow)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/death-row-spaceship-712057c4562d413594beb723f6ec6dd6
Title: Death Row Spaceship
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Spaceship = (props) => {
  const { nodes, materials } = useGLTF('/3dassets/orange_spaceship.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI/2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.Material} position={[-17.254, -15.969, -2.313]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3dassets/orange_spaceship.glb')

export default Spaceship;