/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/3dassets/solar_system.glb 
Author: savounited (https://sketchfab.com/savounited)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/solar-system-paint-3d-fd0cb20fd0794d3886cbbc8cc86ff6c9
Title: Solar System Paint 3D
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SolarSystem (props) {
  const { nodes, materials } = useGLTF('/3dassets/solar_system.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={7}>
        <group position={[0.316, -0.012, 0.091]} scale={0.00035}>
          <mesh geometry={nodes.node_id73_Material_104_0.geometry} material={materials.Material_104} position={[0, 0, 609.922]} scale={9.559} />
          <mesh geometry={nodes.node_id75_Material_105_0.geometry} material={materials.Material_105} position={[625.269, 0, 609.922]} scale={[98.217, 98.217, 392.868]} />
        </group>
        <group position={[0.449, -0.014, 0.224]} scale={0.0002}>
          <mesh geometry={nodes.node_id82_Material_116_0.geometry} material={materials.Material_116} position={[0, 0, 609.922]} rotation={[0, 0, Math.PI / 2]} scale={12.53} />
          <mesh geometry={nodes.node_id84_Material_117_0.geometry} material={materials.Material_117} position={[0, 819.61, 609.922]} rotation={[0, 0, Math.PI / 2]} scale={[128.744, 128.744, 514.976]} />
        </group>
        <mesh geometry={nodes.node_id36_Material_58_0.geometry} material={materials.Material_58} position={[-0.025, -0.012, 0.351]} scale={0.001} />
        <mesh geometry={nodes.node_id42_Material_66_0.geometry} material={materials.Material_66} position={[0.004, -0.012, 0.344]} scale={0.002} />
        <mesh geometry={nodes.node_id30_Material_51_0.geometry} material={materials.Material_51} position={[-0.25, 0.006, 0.325]} scale={0.019} />
        <mesh geometry={nodes.node_id61_Material_89_0.geometry} material={materials.Material_89} position={[0.083, -0.011, 0.326]} scale={0.002} />
        <mesh geometry={nodes.node_id67_Material_96_0.geometry} material={materials.Material_96} position={[0.163, -0.011, 0.324]} scale={0.005} />
        <mesh geometry={nodes.node_id49_Material_73_0.geometry} material={materials.Material_73} position={[0.043, -0.01, 0.337]} scale={0.002} />
        <mesh geometry={nodes.node_id55_Material_81_0.geometry} material={materials.Material_81} position={[0.058, 0.021, 0.321]} scale={0.001} />
        <mesh geometry={nodes.node_id91_Material_126_0.geometry} material={materials.Material_126} position={[0.514, -0.013, 0.353]} scale={0.002} />
      </group>
    </group>
  )
}

useGLTF.preload('/3dassets/solar_system.glb')
