/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/test_tube.glb 
Author: Jackmcm (https://sketchfab.com/Jackmcm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/green-glowing-test-tube-a4ef21580119414ebd2337267573e4ca
Title: Green Glowing Test Tube
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { easing } from 'maath';

export default function TestTube (props) {
  const { nodes, materials } = useGLTF('/3dassets/test_tube.glb')

  useFrame((state, delta) => {
    easing.dampC(materials.blinn2.color, '#d8f3fe', 0.25, delta);
    easing.dampC(materials.blinn1.color, '#ce8f5c', 0.25, delta);
  });
  return (
    <group {...props} dispose={null} position={[2, -10, 0]} scale={[1.5,1.7,1.5]}>
      <mesh geometry={nodes.pCylinder8_blinn2_0.geometry} material={materials.blinn2} position={[0, 5.494, -3.82]} rotation={[-0.285, -0.051, -0.018]} scale={[1, 4.45, 1]} />
      <mesh geometry={nodes.pCylinder9_blinn1_0.geometry} material={materials.blinn1} position={[0.096, 9.536, -4.997]} rotation={[-0.285, -0.051, -0.018]} scale={0.991} />
      <mesh geometry={nodes.pCylinder10_blinn3_0.geometry} material={materials.blinn3} position={[0, 5.76, -3.876]} rotation={[-0.285, -0.051, -0.018]} scale={[0.887, 4.507, 0.887]} />
    </group>
  )
}

useGLTF.preload('/3dassets/test_tube.glb')
